import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { Heebo } from "next/font/google";

const inter = Inter({ subsets: ["latin"],weight:["400","700"] });
const heebo = Heebo({subsets: ["latin"], weight:["400", "700","900"]})

export const metadata: Metadata = {
  title: "Figma_html_css",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={heebo.className}>
        <Header font={inter}/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
